## Andere Datenquellen

Es ist m√∂glich, auch andere Datenquellen als CSV zu benutzen (z.B. SQL oder Json von einer API)

In [34]:
import pandas as pd
import requests as api

In [36]:
json = api.get("https://open.er-api.com/v6/latest/USD")

In [37]:
json.json()

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1693958551,
 'time_last_update_utc': 'Wed, 06 Sep 2023 00:02:31 +0000',
 'time_next_update_unix': 1694046141,
 'time_next_update_utc': 'Thu, 07 Sep 2023 00:22:21 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 73.532435,
  'ALL': 100.348132,
  'AMD': 385.804511,
  'ANG': 1.79,
  'AOA': 832.991858,
  'ARS': 349.99,
  'AUD': 1.56829,
  'AWG': 1.79,
  'AZN': 1.700013,
  'BAM': 1.823114,
  'BBD': 2,
  'BDT': 109.759605,
  'BGN': 1.823058,
  'BHD': 0.376,
  'BIF': 2821.922122,
  'BMD': 1,
  'BND': 1.360857,
  'BOB': 6.92512,
  'BRL': 4.953283,
  'BSD': 1,
  'BTN': 83.05182,
  'BWP': 13.688637,
  'BYN': 2.876194,
  'BZD': 2,
  'CAD': 1.36346,
  'CDF': 2347.973529,
  'CHF': 0.889153,
  'CLP': 859.362241,
  'CNY': 7.302044,
  'COP': 4056.633001,
  'CRC': 537.595684,
  'CUP': 24,
  'CVE': 102.782779,
  'CZK': 22.53003,
  'DJF': 177.721,
  'DKK': 6.952383,
  'DOP': 56.898158,
  'DZD': 136.982881,
  'EGP': 30.916785,
  'ERN': 15,
  'ETB': 55.071865,
  'EUR': 0.932148,
  'FJD': 2.265828,
  'FKP': 0.795689,
  'FOK': 6.954143,
  'GBP': 0.795673,
  'GEL': 2.622374,
  'GGP': 0.795689,
  'GHS': 11.438979,
  'GIP': 0.795689,
  'GMD': 64.097368,
  'GNF': 8562.683318,
  'GTQ': 7.880183,
  'GYD': 209.267321,
  'HKD': 7.841031,
  'HNL': 24.659767,
  'HRK': 7.023234,
  'HTG': 135.375842,
  'HUF': 360.157668,
  'IDR': 15288.79243,
  'ILS': 3.797038,
  'IMP': 0.795689,
  'INR': 83.051955,
  'IQD': 1311.666493,
  'IRR': 41967.900403,
  'ISK': 133.98222,
  'JEP': 0.795689,
  'JMD': 154.719053,
  'JOD': 0.709,
  'JPY': 147.419604,
  'KES': 146.221519,
  'KGS': 87.953607,
  'KHR': 4165.368929,
  'KID': 1.568295,
  'KMF': 458.584432,
  'KRW': 1331.958686,
  'KWD': 0.308549,
  'KYD': 0.833333,
  'KZT': 460.768756,
  'LAK': 19501.698482,
  'LBP': 15000,
  'LKR': 321.158233,
  'LRD': 188.752509,
  'LSL': 19.170947,
  'LYD': 4.816996,
  'MAD': 10.187148,
  'MDL': 17.855285,
  'MGA': 4503.827125,
  'MKD': 56.94474,
  'MMK': 2100.864228,
  'MNT': 3498.737467,
  'MOP': 8.076262,
  'MRU': 38.339351,
  'MUR': 45.577251,
  'MVR': 15.454484,
  'MWK': 1097.490893,
  'MXN': 17.372315,
  'MYR': 4.663001,
  'MZN': 63.872418,
  'NAD': 19.170947,
  'NGN': 755.792106,
  'NIO': 36.635017,
  'NOK': 10.721917,
  'NPR': 132.882911,
  'NZD': 1.700081,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.701312,
  'PGK': 3.639099,
  'PHP': 57.013101,
  'PKR': 307.488631,
  'PLN': 4.181168,
  'PYG': 7314.986389,
  'QAR': 3.64,
  'RON': 4.614405,
  'RSD': 109.110424,
  'RUB': 97.287771,
  'RWF': 1230.217304,
  'SAR': 3.75,
  'SBD': 8.468036,
  'SCR': 13.80168,
  'SDG': 529.777323,
  'SEK': 11.097841,
  'SGD': 1.360858,
  'SHP': 0.795689,
  'SLE': 22.370407,
  'SLL': 22370.40698,
  'SOS': 569.770456,
  'SRD': 38.204648,
  'SSP': 1005.32415,
  'STN': 22.83751,
  'SYP': 12929.583585,
  'SZL': 19.170947,
  'THB': 35.456162,
  'TJS': 10.918212,
  'TMT': 3.49994,
  'TND': 3.120953,
  'TOP': 2.348035,
  'TRY': 26.787121,
  'TTD': 6.73365,
  'TVD': 1.568295,
  'TWD': 31.929712,
  'TZS': 2506.003662,
  'UAH': 36.803833,
  'UGX': 3723.823287,
  'UYU': 37.653879,
  'UZS': 12080.58114,
  'VES': 32.9394,
  'VND': 24040.239317,
  'VUV': 120.84872,
  'WST': 2.771678,
  'XAF': 611.445909,
  'XCD': 2.7,
  'XDR': 0.755926,
  'XOF': 611.445909,
  'XPF': 111.234522,
  'YER': 250.371627,
  'ZAR': 19.177142,
  'ZMW': 20.433177,
  'ZWL': 4609.617759}}

In [38]:
json.json()["rates"]

{'USD': 1,
 'AED': 3.6725,
 'AFN': 73.532435,
 'ALL': 100.348132,
 'AMD': 385.804511,
 'ANG': 1.79,
 'AOA': 832.991858,
 'ARS': 349.99,
 'AUD': 1.56829,
 'AWG': 1.79,
 'AZN': 1.700013,
 'BAM': 1.823114,
 'BBD': 2,
 'BDT': 109.759605,
 'BGN': 1.823058,
 'BHD': 0.376,
 'BIF': 2821.922122,
 'BMD': 1,
 'BND': 1.360857,
 'BOB': 6.92512,
 'BRL': 4.953283,
 'BSD': 1,
 'BTN': 83.05182,
 'BWP': 13.688637,
 'BYN': 2.876194,
 'BZD': 2,
 'CAD': 1.36346,
 'CDF': 2347.973529,
 'CHF': 0.889153,
 'CLP': 859.362241,
 'CNY': 7.302044,
 'COP': 4056.633001,
 'CRC': 537.595684,
 'CUP': 24,
 'CVE': 102.782779,
 'CZK': 22.53003,
 'DJF': 177.721,
 'DKK': 6.952383,
 'DOP': 56.898158,
 'DZD': 136.982881,
 'EGP': 30.916785,
 'ERN': 15,
 'ETB': 55.071865,
 'EUR': 0.932148,
 'FJD': 2.265828,
 'FKP': 0.795689,
 'FOK': 6.954143,
 'GBP': 0.795673,
 'GEL': 2.622374,
 'GGP': 0.795689,
 'GHS': 11.438979,
 'GIP': 0.795689,
 'GMD': 64.097368,
 'GNF': 8562.683318,
 'GTQ': 7.880183,
 'GYD': 209.267321,
 'HKD': 7.841031,
 'HNL': 24.659767,
 'HRK': 7.023234,
 'HTG': 135.375842,
 'HUF': 360.157668,
 'IDR': 15288.79243,
 'ILS': 3.797038,
 'IMP': 0.795689,
 'INR': 83.051955,
 'IQD': 1311.666493,
 'IRR': 41967.900403,
 'ISK': 133.98222,
 'JEP': 0.795689,
 'JMD': 154.719053,
 'JOD': 0.709,
 'JPY': 147.419604,
 'KES': 146.221519,
 'KGS': 87.953607,
 'KHR': 4165.368929,
 'KID': 1.568295,
 'KMF': 458.584432,
 'KRW': 1331.958686,
 'KWD': 0.308549,
 'KYD': 0.833333,
 'KZT': 460.768756,
 'LAK': 19501.698482,
 'LBP': 15000,
 'LKR': 321.158233,
 'LRD': 188.752509,
 'LSL': 19.170947,
 'LYD': 4.816996,
 'MAD': 10.187148,
 'MDL': 17.855285,
 'MGA': 4503.827125,
 'MKD': 56.94474,
 'MMK': 2100.864228,
 'MNT': 3498.737467,
 'MOP': 8.076262,
 'MRU': 38.339351,
 'MUR': 45.577251,
 'MVR': 15.454484,
 'MWK': 1097.490893,
 'MXN': 17.372315,
 'MYR': 4.663001,
 'MZN': 63.872418,
 'NAD': 19.170947,
 'NGN': 755.792106,
 'NIO': 36.635017,
 'NOK': 10.721917,
 'NPR': 132.882911,
 'NZD': 1.700081,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.701312,
 'PGK': 3.639099,
 'PHP': 57.013101,
 'PKR': 307.488631,
 'PLN': 4.181168,
 'PYG': 7314.986389,
 'QAR': 3.64,
 'RON': 4.614405,
 'RSD': 109.110424,
 'RUB': 97.287771,
 'RWF': 1230.217304,
 'SAR': 3.75,
 'SBD': 8.468036,
 'SCR': 13.80168,
 'SDG': 529.777323,
 'SEK': 11.097841,
 'SGD': 1.360858,
 'SHP': 0.795689,
 'SLE': 22.370407,
 'SLL': 22370.40698,
 'SOS': 569.770456,
 'SRD': 38.204648,
 'SSP': 1005.32415,
 'STN': 22.83751,
 'SYP': 12929.583585,
 'SZL': 19.170947,
 'THB': 35.456162,
 'TJS': 10.918212,
 'TMT': 3.49994,
 'TND': 3.120953,
 'TOP': 2.348035,
 'TRY': 26.787121,
 'TTD': 6.73365,
 'TVD': 1.568295,
 'TWD': 31.929712,
 'TZS': 2506.003662,
 'UAH': 36.803833,
 'UGX': 3723.823287,
 'UYU': 37.653879,
 'UZS': 12080.58114,
 'VES': 32.9394,
 'VND': 24040.239317,
 'VUV': 120.84872,
 'WST': 2.771678,
 'XAF': 611.445909,
 'XCD': 2.7,
 'XDR': 0.755926,
 'XOF': 611.445909,
 'XPF': 111.234522,
 'YER': 250.371627,
 'ZAR': 19.177142,
 'ZMW': 20.433177,
 'ZWL': 4609.617759}

In [42]:
readJson = pd.DataFrame.from_dict(json.json()["rates"], orient="index")
readJson.rename(columns={0: "Rates"})

           Rates
USD     1.000000
AED     3.672500
AFN    73.532435
ALL   100.348132
AMD   385.804511
..           ...
XPF   111.234522
YER   250.371627
ZAR    19.177142
ZMW    20.433177
ZWL  4609.617759

[162 rows x 1 columns]

In [43]:
pd.read_json("https://open.er-api.com/v6/latest/USD")

,result,provider,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,time_eol_unix,base_code,rates
AED,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,3.672500
AFN,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,73.532435
ALL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,100.348132
AMD,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,385.804511
ANG,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,1.790000
...,...,...,...,...,...,...,...,...,...,...,...
XPF,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,111.234522
YER,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,250.371627
ZAR,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,19.177142
ZMW,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,20.433177
ZWL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1693958551,"Wed, 06 Sep 2023 00:02:31 +0000",1694045981,"Thu, 07 Sep 2023 00:19:41 +0000",0,USD,4609.617759

## Daten aus der Datenbank

In [44]:
import sqlite3 as sql
connection = sql.connect("Test.db")

cursor = connection.cursor()

cursor.execute("create table test(id integer primary key, name varchar(30))")
cursor.execute("insert into test (id, name) values(1, 'Max1')")
cursor.execute("insert into test (id, name) values(2, 'Max2')")
cursor.execute("insert into test (id, name) values(3, 'Max3')")

data = pd.read_sql("SELECT * FROM test", con=connection)

In [45]:
data

   id  name
0   1  Max1
1   2  Max2
2   3  Max3

## Export von Daten

In [46]:
readJson.to_csv("json.csv")

In [47]:
readJson.to_json("json.json")

In [48]:
import openpyxl  # Muss separat installiert werden
readJson.to_excel("json.excel")

ValueError: No engine for filetype: 'excel'